/*
================================================================================
DFI: New permission requests for MSS-level access (approved)
================================================================================
Creates NEW permission requests for 18 users. Each request grants RLS scope at
MSS level (Global, All Clients, MSS Overall, BR_TOTAL) and is created as APPROVED.
Does NOT touch RLSFUMApprovers (approvers).

RequestCode is generated by dbo.GeneratePermissionRequestCode (same as the app),
so no duplicate codes with seed data or other requests. One request per user;
full RLS chain: PermissionRequests -> PermissionHeaders -> RLSPermissions ->
RLSPermissionFUMDetails.

Requires: dbo.GeneratePermissionRequestCode exists and returns RequestCode (and
optionally DomainLoV). Run after 0-Global and 1-DFI. Safe to run multiple times
(creates 18 new requests each run; skip if these users already have MSS access).
================================================================================
*/
SET NOCOUNT ON;

DECLARE @WorkspaceId INT;
DECLARE @SecurityModelId INT;
DECLARE @SecurityTypeLoVId INT;
DECLARE @CreatedBy NVARCHAR(255) = N'sakurahelp@dentsu.com';
DECLARE @RequestCode NVARCHAR(50);
DECLARE @RequestedFor NVARCHAR(255);
DECLARE @PermissionRequestId INT;
DECLARE @PermissionHeaderId INT;
DECLARE @RLSPermissionsId INT;

SELECT @WorkspaceId = Id FROM dbo.Workspaces WHERE WorkspaceCode = N'DFI' AND ISNULL(ValidTo, '9999-12-31') >= CAST(GETDATE() AS DATE);
SELECT @SecurityModelId = Id FROM dbo.WorkspaceSecurityModels WHERE SecurityModelCode = N'DFI-Default' AND ISNULL(ValidTo, '9999-12-31') >= CAST(GETDATE() AS DATE);
SELECT @SecurityTypeLoVId = Id FROM dbo.LoVs WHERE LoVType = N'SecurityType' AND LoVValue = N'FUM' AND ISNULL(ValidTo, '9999-12-31') >= CAST(GETDATE() AS DATE);

IF @WorkspaceId IS NULL OR @SecurityModelId IS NULL OR @SecurityTypeLoVId IS NULL
BEGIN
    RAISERROR('Missing DFI WorkspaceId, DFI-Default SecurityModelId, or FUM SecurityTypeLoVId. Run 0-Global first.', 16, 1);
    RETURN;
END

-- Table to capture proc output (column names must match what GeneratePermissionRequestCode returns)
CREATE TABLE #ProcResult (RequestCode NVARCHAR(50), DomainLoV NVARCHAR(50) NULL);

-- List of users to grant MSS-level access
CREATE TABLE #Users (RequestedFor NVARCHAR(255) NOT NULL);
INSERT INTO #Users (RequestedFor) VALUES
    (N'akansha.kothari@dentsu.com'),
    (N'anand.chougule@dentsu.com'),
    (N'anshul.kumawat@dentsu.com'),
    (N'Bharath.S@dentsu.com'),
    (N'Devraj.Viswanathan@dentsu.com'),
    (N'Gurvinder.Singh1@dentsu.com'),
    (N'Joish.Sandeep@dentsu.com'),
    (N'Kate.Rudwick@dentsu.com'),
    (N'Lokesh.S@dentsu.com'),
    (N'md.anwar@dentsu.com'),
    (N'Naresh.Kumarsb@dentsu.com'),
    (N'praveen.kumar2@dentsu.com'),
    (N'Rakesh.Raju@dentsu.com'),
    (N'Supreet.Kaur@dentsu.com'),
    (N'Terry.Newell@dentsu.com'),
    (N'Varun.Sharma5@dentsu.com'),
    (N'Kevinde.Silva@dentsu.com'),
    (N'yashwanth.cherukuri@dentsu.com');

DECLARE user_cursor CURSOR LOCAL FAST_FORWARD FOR
    SELECT RequestedFor FROM #Users;

OPEN user_cursor;
FETCH NEXT FROM user_cursor INTO @RequestedFor;

WHILE @@FETCH_STATUS = 0
BEGIN
    -- Get next RequestCode from proc (no duplicate with seed or app-created requests)
    DELETE FROM #ProcResult;
    INSERT INTO #ProcResult (RequestCode, DomainLoV)
    EXEC dbo.GeneratePermissionRequestCode @WorkspaceId = @WorkspaceId;

    SELECT @RequestCode = RequestCode FROM #ProcResult;
    IF @RequestCode IS NULL OR LTRIM(RTRIM(@RequestCode)) = N''
    BEGIN
        RAISERROR('GeneratePermissionRequestCode returned empty RequestCode for WorkspaceId %d.', 16, 1, @WorkspaceId);
        CLOSE user_cursor;
        DEALLOCATE user_cursor;
        DROP TABLE #ProcResult;
        DROP TABLE #Users;
        RETURN;
    END

    -- 1) PermissionRequests
    INSERT INTO dbo.PermissionRequests
        (RequestCode, RequestedFor, RequestedBy, LMApprover, RequestStatus, RequestReason, WorkspaceId, CreatedAt, CreatedBy, UpdatedAt, UpdatedBy)
    VALUES
        (@RequestCode, @RequestedFor, @RequestedFor, @RequestedFor, 3, N'MSS level access for DFI', @WorkspaceId, GETDATE(), @CreatedBy, GETDATE(), @CreatedBy);
    SET @PermissionRequestId = SCOPE_IDENTITY();

    -- 2) PermissionHeaders (RLS, Approved)
    INSERT INTO dbo.PermissionHeaders
        (PermissionRequestId, PermissionType, ApprovalStatus, Approvers, ApprovedBy, ApprovedAt, ApproveNote,
         RejectedBy, RejectedAt, RejectNote, RevokedBy, RevokedAt, RevokeNote, CreatedAt, CreatedBy, UpdatedAt, UpdatedBy)
    VALUES
        (@PermissionRequestId, 1, 2, N'Terry.Newell@dentsu.com', N'Terry.Newell@dentsu.com', GETDATE(), N'Approved',
         NULL, NULL, NULL, NULL, NULL, NULL, GETDATE(), @CreatedBy, GETDATE(), @CreatedBy);
    SET @PermissionHeaderId = SCOPE_IDENTITY();

    -- 3) RLSPermissions (DFI-Default, FUM)
    INSERT INTO dbo.RLSPermissions
        (PermissionHeaderId, SecurityModelId, SecurityTypeLoVId, AdditionalDetailsJSON, CreatedAt, CreatedBy, UpdatedAt, UpdatedBy)
    VALUES
        (@PermissionHeaderId, @SecurityModelId, @SecurityTypeLoVId, N'{}', GETDATE(), @CreatedBy, GETDATE(), @CreatedBy);
    SET @RLSPermissionsId = SCOPE_IDENTITY();

    -- 4) RLSPermissionFUMDetails — MSS level scope
    INSERT INTO dbo.RLSPermissionFUMDetails
        (RLSPermissionsId, EntityKey, EntityHierarchy, CountryKey, CountryHierarchy, ClientKey, ClientHierarchy,
         MSSKey, MSSHierarchy, ProfitCenterKey, ProfitCenterHierarchy, CreatedAt, CreatedBy, UpdatedAt, UpdatedBy)
    VALUES
        (@RLSPermissionsId, N'Global', N'Global', NULL, NULL, N'All Clients', N'All Clients',
         N'Overall', N'Overall', N'BR_TOTAL', N'BPCBrand', GETDATE(), @CreatedBy, GETDATE(), @CreatedBy);

    FETCH NEXT FROM user_cursor INTO @RequestedFor;
END

CLOSE user_cursor;
DEALLOCATE user_cursor;
DROP TABLE #ProcResult;
DROP TABLE #Users;

PRINT 'Done. 18 new DFI permission requests for MSS-level access (RequestCodes from proc), all approved.';

GO
